api_platform:
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    show_webby: false
    keep_legacy_inflector: false
    exception_to_status:
        App\Exception\LimitExtractionException: 409
        App\Exception\Register\FailedTokenParseException: 422
        App\Exception\Register\TooOldTokenException: 422
        App\Exception\Register\UsernameNotAvailableException: 422
