api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Model'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    show_webby: false
