framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            extract:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            sell:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            sell_cargo:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            cargo_quantity_check:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            App\Message\Extract\Extract: extract
            App\Message\Sell\Sell: sell
            App\Message\Sell\SellCargo: sell_cargo
            App\Message\Cargo\CargoQuantityCheck: cargo_quantity_check
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
